q: 0
server: 1
partsize: 10
mp4: false
nocleanup: false
dlVideoOnce: false
keepAllVideos: false
fileName: '[${service}] ${showTitle} - S${season}E${episode} [${height}p]'
dubLang:
  - spa-ES
  - spa
  - jpn
dlsubs:
  - es-ES
  - es-419
  - en-US
defaultAudio: spa-ES
vstream: androidtv
astream: android
tsd: false
ffmpegOptions:
  - '-c:v libx265'
  - '-crf 23'
  - '-preset fast'
  - '-c:a copy'
audioPriority:
  - spa-ES
  - spa
  - jpn
subtitlePriority:
  - es-ES
  - es-419
  - en-US
  - none
x265Preset: none
encodingPreset: h265_1080p24_high_crf
metadataProviders:
  - anilist
  - tmdb
  - crunchy
  - anidb
  - tvdb
scanConcurrency: 1
threads: 0
defaultSub: es-ES
